### PR TITLE
Fix keylog mode not working correctly on certain OpenSSL versions

### LINKED ISSUE #533: Keylog capture not working with OpenSSL 1.1.0
**Describe the bug**
﻿
When using the `ecapture` tool with OpenSSL 1.1.0 to capture keylog data with the `-m keylog` option, no output is generated.
﻿
**To Reproduce**
﻿
﻿
1. Clone the `ecapture` repository using `git clone https://github.com/gojue/ecapture.git`
2. Compile OpenSSL 1.1.0a from source and install it in `/opt/openssl`
3. Compile `curl` with the provided OpenSSL 1.1.0 library
4. Start `ecapture` in text mode to capture TLS traffic using `sudo ./bin/ecapture tls --libssl=/opt/openssl/lib/libssl.so.1.1`
5. Initiate an HTTPS request using a tool compiled against the same OpenSSL 1.1.0 library (e.g., `curl`)
6. Observe that the decrypted TLS traffic is correctly captured and displayed
7. Stop the `ecapture` process
8. Attempt to capture keylog data using `sudo ./bin/ecapture tls -m keylog -k ecapture.txt --libssl=/opt/openssl/lib/libssl.so.1.1`
9. No output is generated in the `ecapture.txt` file
﻿

**Expected behavior**
﻿
When using the `-m keylog` option with OpenSSL 1.1.0, `ecapture` should capture and output keylog data to the specified file (`ecapture.txt` in this case).
﻿

**Screenshots**
﻿
I cannot provide screenshots directly, but here is the relevant output from the terminal:
﻿
```bash
$ sudo ./bin/ecapture tls --libssl=/opt/openssl/lib/libssl.so.1.1
# ... TLS decryption output ...
﻿
$ sudo ./bin/ecapture tls -m keylog -k ecapture.txt --libssl=/opt/openssl/lib/libssl.so.1.1
# No output in ecapture.txt
```
﻿
**Linux Server:**
﻿
- OS: Ubuntu 20.04.6 LTS
- Arch: x86_64
- Kernel Version: 5.4.0-176-generic
- Version: [a8acece](https://github.com/gojue/ecapture/commit/a8acecee080779e1a55a1a57d62e6d682ff21661)
﻿

**Additional context**
﻿
This issue seems to be specific to the OpenSSL 1.1.0 version. I have tried reproducing this issue on multiple Linux distributions and kernel versions, and the behavior is consistent with OpenSSL 1.1.0. It seems that the keylog capture functionality is not working as expected with this particular OpenSSL version, despite TLS decryption working correctly. I would appreciate if this issue could be investigated and resolved for OpenSSL 1.1.0 compatibility.

### PR DESCRIPTION
**Pull request by AmazingPP**
Fixes #533 

The root cause of the problem was that the offset of the client_random member within the `ssl3_state_st` structure varies across different OpenSSL versions.

Although the offsets for the `ssl3_state_st->client_random` member (`SSL3_STATE_ST_CLIENT_RANDOM`) were already generated for all supported OpenSSL versions, but they were not being utilized correctly.
﻿
To solve this issue, the existing `SSL3_STATE_ST_CLIENT_RANDOM` offsets have been integrated into the code, ensuring that ecapture can accurately retrieve the `client_random` value from the correct location within the `ssl3_state_st` structure, regardless of the OpenSSL version being used.

### CODE REVIEW

File: user/module/probe_openssl_lib.go [hunk 1]
```diff
@@ -104,7 +104,7 @@ func (m *MOpenSSLProbe) initOpensslOffset() {
 
 	// openssl 1.1.0a - 1.1.0l
 	for ch := 'a'; ch <= MaxSupportedOpenSSL110Version; ch++ {
-		m.sslVersionBpfMap["openssl 1.1.0"+string(ch)] = "openssl_1_1_1a_kern.o"
+		m.sslVersionBpfMap["openssl 1.1.0"+string(ch)] = "openssl_1_1_0a_kern.o"
```
Comment (cfc4n) [inline user/module/probe_openssl_lib.go:107]: It looks like the wrong bytecode file was selected here?

Does fixing it here mean we don't need to fix `openssl_masterkey.h` anymore?

**Review by cfc4n — COMMENTED** [review]
isn't the `ssl3_state_st` structure of the 1.1.0 series like this?

File: user/module/probe_openssl_lib.go (hunk 1 above)
Comment (AmazingPP) [reply user/module/probe_openssl_lib.go:107]: > It looks like the wrong bytecode file was selected here?

Yes.

> Does fixing it here mean we don't need to fix `openssl_masterkey.h` anymore?

No.  That is not enough.

https://github.com/openssl/openssl/blob/OpenSSL_1_1_0a/ssl/ssl_locl.h#L1140-L1147
https://github.com/openssl/openssl/blob/OpenSSL_1_1_1a/ssl/ssl_locl.h#L1518-L1525

Note that in `ssl3_state_st` structure for OpenSSL versions 1.1.0a and 1.1.1a, the types of `read_mac_secret_size` and `write_mac_secret_size` members differ. On 64-bit systems, their sizes are not the same, resulting in a different offset for `client_random` member.

**Comment by AmazingPP** [comment]
> isn't the `ssl3_state_st` structure of the 1.1.0 series like this?

Yes, it's not just a minor difference between 1.1.0 and 1.1.1. The `ssl3_state_st` structure in the 1.0.2 series is completely different from the 1.1.0 and 1.1.1 series.

**Review by cfc4n — APPROVED** [review]
LGTM, thanks.
