### PR TITLE
fix #500 to avoid potential hang and event loss

### LINKED ISSUE #500: Potential hang for eCapture under really rare circumstances
**Describe the bug**
Due to the design flaw of `iworker` model, under rare condition, eCapture might hang. 

This bug is discovered through code review and to reliably prove it, I design a PoC(Proof of Concept) .

**To Reproduce**

This is my poc commit https://github.com/ruitianzhong/ecapture/commit/a2e41118df96cf7464152cd1847e5bcbb51b47be.

It essentially do two thing: 
* Firstly add a unit test that write a event(force the EventProcessor.Serve() go routine to create a worker) and sleep two second(wait the worker to be deleted). Finally, the unit test write tons of the same event.
* Secondly inject some delay in the following code before ew.Close (in `pkg/event_processor/iworker.go`):
```go
if ew.tickerCount > MaxTickerCount {
				//ew.processor.GetLogger().Printf("eventWorker TickerCount > %d, event closed.", MaxTickerCount)
				time.Sleep(time.Second*15) // inject some delay here (just to show the possible interleaving)
				ew.Close()
				return
			}
``` 
That is reasonable, because we should assume that go routine might be scheduled out at any time.

On the poc commit, run 
```bash
go test  -v ./pkg/event_processor/  -run TestHang 
```

The output:
```bash
begin Write if you can not see end later, it mean eventProcessor.Serve routine might hang
end Write
begin Write if you can not see end later, it mean eventProcessor.Serve routine might hang
end Write
begin Write if you can not see end later, it mean eventProcessor.Serve routine might hang
end Write
begin Write if you can not see end later, it mean eventProcessor.Serve routine might hang
```
Obviously, eCapture hang.

**Expected behavior**
eCapture might be slowed down, but should not hang.

### PR DESCRIPTION
**Pull request by ruitianzhong**
* add `IfUsed()` for worker to check if it is used.
* add `Get()` for  routine that generates event before using the worker and `Put()` when after using the worker. They should not be called concurently(only one producer). So it panics if unexpected behavior happen. 
* add clean up logic for ew.incoming and return only after both the ew.incoming is empty and  ew is not used. 

The reasoning for that is as follows.

When returned from ew.Close(), there are two possiblities:
1) no routine can touch it.
2) one routine can still touch ew because getWorkerByUUID()
**happen before** ew.Close()

When no routine can touch it (i.e.,ew.IfUsed == false),
we just drain the ew.incoming and return.

When one routine can touch it (i.e.,ew.IfUsed == true), we ensure
that we only return after the routine can not touch it
(i.e.,ew.IfUsed == false). At this point, we can ensure that no
other routine will touch it and send events through the ew.incoming.
So, we return.

Because eworker has been deleted from workqueue after ew.Close()
(ordered by a workqueue lock), at this point, we can ensure that
no ew will not be touched even **in the future**. So the return is
safe.

Finally, to verify it, in https://github.com/ruitianzhong/ecapture/commit/e5bce57a5b97425383ba12ee41b56f433caaa8aa , run `go test  -v ./pkg/event_processor/  -run TestHang ` , no hang happened.

Because the `poc` inject delay to reliably reproduce the hang, I do not add it as a unit test in bug-fix branch.

### CODE REVIEW

File: pkg/event_processor/iworker.go [hunk 1]
```diff
@@ -127,12 +132,45 @@ func (ew *eventWorker) parserEvents() []byte {
...
+					safe.
+
+				*/
+				for {
+					select {
+					case e := <-ew.incoming:
+						ew.writeEvent(e)
+					default:
+						if ew.IfUsed() {
+							continue
```
Comment (cfc4n) [inline pkg/event_processor/iworker.go:168]: Does it need to sleep here for a while? Otherwise, will it bring the problem of CPU preemption?

**Review by cfc4n — CHANGES_REQUESTED** [review]

File: pkg/event_processor/iworker.go (hunk 1 above)
Comment (ruitianzhong) [reply pkg/event_processor/iworker.go:169]: I have added the Sleep to address your concern.

But in my opinion, this would not bring the problem of CPU preemption.

Firstly, the total time when ew.used is set to true is expected to be short( just like the spinlock) 

Secondly, according to [Go 1.14 Release Note](https://go.dev/doc/go1.14#runtime):

> Goroutines are now asynchronously preemptible. As a result, loops without function calls no longer potentially deadlock the scheduler or significantly delay garbage collection. This is supported on all platforms except windows/arm, darwin/arm, js/wasm, and plan9/*.

There exists function call in the `for select` loop , and it will not bring problem to deadlock the scheduler or delay GC.

Comment (cfc4n) [reply pkg/event_processor/iworker.go:169]: From my experience, CPU preemption does occur. However, I have not paid attention to the official documentation of Golang. 

Here is a simple example:
```golang
package main

import (
	"fmt"
)

func main() {
	incoming := make(chan int, 1024)

	for {
		select {
		case e := <-incoming:
			fmt.Println("incoming:", e)
		default:
			if true {
				fmt.Println("default")
				continue
			}
			return
		}
	}
	fmt.Println("end")
}
```

So, I think the `sleep` code here  is necessary.

**Review by cfc4n — APPROVED** [review]
LGTM, thanks.
