### PR TITLE
fix: pcap filter not work as expected

### LINKED ISSUE #673: arp packet found in pcap file on tls -m pcap mode
**Describe the bug**
When using tls -m pcap mode, arp packets are found in the obtained pcap file . There is a problem with specifying or not specifying capture filter parameters. Is this a bug? 

**To Reproduce**
 ./ecapture tls -m pcap -i ens1f0  --pcapfile=all.pcap

```
# tcpdump -nn -r all.pcap  'arp'
reading from file all.pcap, link-type EN10MB (Ethernet)
dropped privs to tcpdump
15:52:03.990048 ARP, Request who-has 192.168.10.108 tell 192.168.10.1, length 46
15:52:05.003197 ARP, Request who-has 192.168.10.108 tell 192.168.10.1, length 46
15:52:07.003957 ARP, Request who-has 192.168.10.108 tell 192.168.10.1, length 46
15:52:07.324029 ARP, Request who-has 192.168.10.108 tell 192.168.10.1, length 46
```

# os info
```
# cat /etc/os-release 
NAME="openEuler"
VERSION="22.03 (LTS-SP4)"
ID="openEuler"
VERSION_ID="22.03"
PRETTY_NAME="openEuler 22.03 (LTS-SP4)"
ANSI_COLOR="0;31"

# uname -a
Linux zhm-cd-vm 5.10.0-216.0.0.115.oe2203sp4.x86_64 #1 SMP Thu Jun 27 15:13:44 CST 2024 x86_64 x86_64 x86_64 GNU/Linux

# ecapture -v
eCapture version:	linux_amd64:v0.8.9:6.5.0-1025-azure
```

### PR DESCRIPTION
**Pull request by yuweizzz**
The pcap filter now doesn't take effect for packet protocols that are not IP or IPv6, such as ARP.

```
bin/ecapture gnutls -m pcap -i enp0s3  port 443 and not arp
2024-12-04T14:30:59+08:00 INF AppName="eCapture(旁观者)"
2024-12-04T14:30:59+08:00 INF HomePage=https://ecapture.cc
2024-12-04T14:30:59+08:00 INF Repository=https://github.com/gojue/ecapture
2024-12-04T14:30:59+08:00 INF Author="CFC4N <cfc4ncs@gmail.com>"
2024-12-04T14:30:59+08:00 INF Description="Capturing SSL/TLS plaintext without a CA certificate using eBPF. Supported on Linux/Android kernels for amd64/arm64."
2024-12-04T14:30:59+08:00 INF Version=linux_amd64:-20241202-b231985:6.1.0-22-amd64
2024-12-04T14:30:59+08:00 INF Listen=localhost:28256
2024-12-04T14:30:59+08:00 INF eCapture running logs logger=
2024-12-04T14:30:59+08:00 INF the file handler that receives the captured event eventCollector=
2024-12-04T14:30:59+08:00 WRN ========== module starting. ==========
2024-12-04T14:30:59+08:00 INF listen=localhost:28256
2024-12-04T14:30:59+08:00 INF https server starting...You can update the configuration file via the HTTP interface.
2024-12-04T14:30:59+08:00 INF Kernel Info=6.1.0 Pid=411712
2024-12-04T14:30:59+08:00 INF BTF bytecode mode: CORE. btfMode=0
2024-12-04T14:30:59+08:00 INF GnuTlsProbe init eBPFProgramType=PcapNG model=PcapNG
2024-12-04T14:30:59+08:00 INF module initialization. isReload=false moduleName=EBPFProbeGNUTLS
2024-12-04T14:30:59+08:00 INF Module.Run()
2024-12-04T14:30:59+08:00 INF GnuTLS version found Version=3.7.9
2024-12-04T14:30:59+08:00 INF GnuTLS binary path binaryPath=/lib/x86_64-linux-gnu/libgnutls.so.30 elfType=2
2024-12-04T14:30:59+08:00 INF BPF bytecode loaded bytecode filename=user/bytecode/gnutls_3_7_7_kern_core.o
2024-12-04T14:30:59+08:00 INF Hook type: Gnutls elf ElfType=2 IFindex=2 IFname=enp0s3 PcapFilter="port 443 and not arp" binrayPath=/lib/x86_64-linux-gnu/libgnutls.so.30
2024-12-04T14:30:59+08:00 INF Hook masterKey function: gnutls_handshake
2024-12-04T14:30:59+08:00 INF target all process.
2024-12-04T14:30:59+08:00 INF packets saved into pcapng file. pcapng path=/usr/local/src/ecapture/save.pcapng
2024-12-04T14:30:59+08:00 INF perfEventReader created mapSize(MB)=4
2024-12-04T14:30:59+08:00 INF perfEventReader created mapSize(MB)=4
2024-12-04T14:30:59+08:00 INF module started successfully. isReload=false moduleName=EBPFProbeGNUTLS
2024-12-04T14:31:05+08:00 INF CLIENT_RANDOM save success ClientRandom=c0c59329aaed4a5bcad60c18defab6bbeb9fa741648700fcb0e19cd2b6157549 TlsVersion=GNUTLS_TLS1_2 eBPFProgramType=PcapNG
2024-12-04T14:31:05+08:00 INF packets saved into pcapng file. count=26
2024-12-04T14:31:11+08:00 INF packets saved into pcapng file. count=2 ----- arp packet
2024-12-04T14:31:13+08:00 INF packets saved into pcapng file. count=4 ----- arp packet
2024-12-04T14:31:15+08:00 INF packets saved into pcapng file. count=4 ----- arp packet
2024-12-04T14:31:17+08:00 INF packets saved into pcapng file. count=4 ----- arp packet
^C2024-12-04T14:31:20+08:00 INF packets saved into pcapng file. count=40
```

```
curl https://xxx.com
arping x.x.x.x
```

reason:
In #586, the inject function migrated, not work for all packet anymore.

should fix #673

### CODE REVIEW

File: kern/tc.h [hunk 1]
```diff
@@ -131,29 +131,28 @@ static __always_inline int capture_packets(struct __sk_buff *skb, bool is_ingres
     // packet data
     unsigned char *data_start = (void *)(long)skb->data;
     unsigned char *data_end = (void *)(long)skb->data_end;
-    if (data_start + sizeof(struct ethhdr) > data_end) {
+
+    // packet length check
+    if (data_start + sizeof(struct ethhdr) > data_end || 
+        data_start + sizeof(struct ethhdr) + sizeof(struct iphdr) > data_end)
```
Comment (Asphaltt) [inline kern/tc.h:137]: `data_start + sizeof(struct ethhdr) > data_end` is unnecessary here. `data_start + sizeof(struct ethhdr) + sizeof(struct iphdr) > data_end` is enough. As we filter ethernet layer info alongside IP layer info at most time.

**Comment by Asphaltt** [comment]
Could you please improve commit title and commit message?

**Review by Asphaltt — CHANGES_REQUESTED** [review]

**Review by Asphaltt — APPROVED** [review]

**Review by cfc4n — APPROVED** [review]
LGTM, Thanks.
